INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (1,'SAFE -100','Tab','Cefixime I.P.','100 mg','10x10','Alu-Alu','720','210');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (2,'SAFE -200','Tab','Cefixime I.P.','200 mg','10x10','Alu-Alu','1,050.00','350');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (3,'SAFE - O','Tab','Cefixime I.P.','200 mg','10x10','Alu-Alu','1,500.00','460');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (4,'SAFE - O','Tab','Ofloxacin I.P.','200 mg','10x10','Alu-Alu','1,500.00','460');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (5,'SAFE - AZ','Tab','Cefixime I.P.','200 mg','10x1x10','Mono Alu-Alu','2,200.00','750');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (6,'SAFE - AZ','Tab','Azithromycin I.P.','250 mg','10x1x10','Mono Alu-Alu','2,200.00','750');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (7,'SAFE - AZ','Tab','Lactic Acid bacillus','60 m.s.','10x1x10','Mono Alu-Alu','2,200.00','750');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (8,'ACPOD-100','Tab','Cefpodoxime Proxetil I.P.','100 mg','10x10','Alu-Alu','1,100.00','290');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (9,'ACPOD-200','Tab','Cefpodoxime Proxetil I.P','200 mg','10x10','Alu-Alu','2,100.00','550');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (10,'ACPOD-CV-325','Tab','Cefpodoxime Proxetil I.P','200 mg','1x10x6','Alu-Alu','2,100.00','600');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (11,'ACPOD-CV-325','Tab','Diluted Pota.','125 mg','1x10x6','Alu-Alu','2,100.00','600');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (12,'ACPOD-CV-325','Tab','Clavulanate I.P.',NULL,'1x10x6','Alu-Alu','2,100.00','600');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (13,'GLIVO-250','Tab','Levofloxacin I.P.','250 mg','10x10','Blister','460','155');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (14,'GLIVO-500','Tab','Levofloxacin I.P.','500 mg','10x10','Alu-Alu','800','240');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (15,'ALMAC-250','Tab','Azithromycin I.P.','250 mg','10X6','Blister','650','240');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (16,'ALMAC-500','Tab','Azithromycin I.P.','500 mg','10x1x3','Blister','650','240');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (17,'FLIT 200','Tab','Ofloxacin I.P.','200 mg','10x10','Blister','550','120');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (18,'FLIT-OZ','Tab','Ofloxacin I.P.','200 mg','10x10','Blister','850','200');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (19,'FLIT-OZ','Tab','Ornidazole I.P.','500 mg','10x10','Blister','850','200');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (20,'2 MOX 500','Cap','Amoxycillin I.P.','500 mg','10x10','Blister','700','240');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (21,'2 MOX CV-375','Tab','Amoxycillin I.P.,','250 mg','10x1x6','Alu-Alu Mono','1,100.00','340');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (22,'2 MOX CV-375','Tab','Dilute Pota Clavulanate','125 mg','10x1x6','Alu-Alu Mono','1,100.00','340');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (23,'2 MOX CV-625','Tab','Amoxycillin I.P.,','500 mg','10x1x6','Alu-Alu Mono','1,180.00','399');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (24,'2 MOX CV-625','Tab','Dilute Pota Clavulanate','125 mg','10x1x6','Alu-Alu Mono','1,180.00','399');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (25,'2 MOX CV-1000','Tab','Amoxycillin I.P.,','875 mg','10x1x6','Alu-Alu','2,100.00','570');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (26,'2 MOX CV-1000','Tab','Dilute Pota Clavulanate','125 mg','10x1x6','Alu-Alu','2,100.00','570');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (27,'RDNAC-P','Tab','Aceclofenac I.P.','100 mg','10x10','Blister','450','70');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (28,'RDNAC-P','Tab','Paracetamol I.P.','325mg','10x10','Blister','450','70');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (29,'ONTRON','Tab','Ondansetron','4 mg','10x10',NULL,'440','77');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (30,'RDNAC-MR','Tab','Aceclofenac I.P.','100 mg','10x10','Alu-Alu','700','140');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (31,'RDNAC-MR','Tab','Paracetamol I.P.','325 mg','10x10','Alu-Alu','700','140');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (32,'RDNAC-MR','Tab','Chlorzoxazone U.S.P.','250 mg','10x10','Alu-Alu','700','140');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (33,'RDNAC-SP','Tab','Aceclofenac I.P.','100 mg','10x10','Alu-Alu','850','140');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (34,'RDNAC-SP','Tab','Paracetamol I.P.','325 mg','10x10','Alu-Alu','850','140');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (35,'RDNAC-SP','Tab','Serratiopeptidase I.P.','15 mg','10x10','Alu-Alu','850','140');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (36,'RDNAC-T','Tab','Aceclofenac I.P.','100 mg','10x10','Alu Alu','1,600.00','460');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (37,'RDNAC-T','Tab','Thiocolchicoside','4 mg','10x10','Alu Alu','1,600.00','460');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (38,'RAMBO-P','Tab','Nimesulide B.P.','100 mg','20x10','Blister','800','95');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (39,'RAMBO-P','Tab','Paracetamol I.P.','325 mg','20x10','Blister','800','95');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (40,'RAMBO','Tab','Nimesulide','100 mg','10x10','Blister','290','55');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (41,'RACETAMOL','Tab','Paracetamol I.P.','650 mg','10 x 10','Blister','200','66');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (42,'RABTUS-D','Tab','Rabeprazole Sodium I.P.','20 mg','10x10','Alu-Alu','650','85');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (43,'RABTUS-D','Tab','Domperidone I.P.','10 mg','10x10','Alu-Alu','650','85');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (44,'RABTUS-DSR','Cap','Rabeprazole Sodium I.P. (Enteric Coated Pellets)','20 mg','10x10','Alu-Alu','800','150');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (45,'RABTUS-DSR','Cap','Domperidone I.P. (Sustained Release Pellets)','30 mg','10x10','Alu-Alu','800','150');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (46,'RABTUS-L','Cap','Rabeprazole Sodium I.P. (enteric coated pellets)','20 mg','10x10','Alu-Alu','1,500.00','280');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (47,'RABTUS-L','Cap','Levosulpride (sustained release pellets)','75mg','10x10','Alu-Alu','1,500.00','280');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (48,'EMEE','Cap','Esomeprazole','40 mg','10x10','Alu-Alu','800','175');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (49,'EMEE','Cap','Domperidone','30 mg','10x10','Alu-Alu','800','175');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (50,'RDPAN-40','Tab','Pantoprazole I.P.','40 mg','10x10','Alu-Alu','600','95');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (51,'RDPAN-40 D','Tab','Pantoprazole I.P.','40 mg','10x10','Alu-Alu','660','100');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (52,'RDPAN-40 D','Tab','Domperidone I.P.','10 mg','10x10','Alu-Alu','660','100');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (53,'RDPAN-DSR','Cap','Pantoprazole I.P. (enteric coated pellets)','40mg','10x10','Alu-Alu','1,000.00','165');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (54,'RDPAN-DSR','Cap','DomperidoneI.P. (sustainedrelease pellets)','30 mg','10x10','Alu-Alu','1,000.00','165');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (55,'OMZEE','Cap','Omeprazole I.P.','20 mg','10x10','Alu-Alu','400','85');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (56,'OMZEE','Cap','Domperidone I.P. (enteric coated granules)','10 mg','10x10','Alu-Alu','400','85');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (57,'GENOLIV-300','Tab','Ursodeoxycholic Acid U.S.P.','300 mg','1X10x10','Alu-Alu','3,000.00','1,050.00');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (58,'RIZO COLD','Tab','Paracetamol I.P.','500 mg','10 X 10','Blister','450','85');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (59,'RIZO COLD','Tab','Phenylephrine Hydrochloride I.P.','5 mg','10 X 10','Blister','450','85');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (60,'RIZO COLD','Tab','Cetirizine Dihydrochloride I.P.','5 mg','10 X 10','Blister','450','85');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (61,'ESCORT-6','Tab','Deflazacort','6 mg','10x10','Alu-Alu','820','160');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (62,'FLUCO 150','Tab','Fluconazole I.P.','150 mg','1 x 10','Blister','129.8','51.35');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (63,'RD-CET','Tab','Levocetrizine','5 mg','20 x 10','Blister','700','88');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (64,'RD-CET','Tab','Dihydrochloride I.P.',NULL,'20 x 10','Blister','700','88');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (65,'RDCET-M','Tab','Montelukast','10 mg','10x10','Alu-Alu','1,000.00','180');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (66,'RDCET-M','Tab','Levocetirizine Dihydrochloride I.P.','5 mg','10x10','Alu-Alu','1,000.00','180');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (67,'ITAZOLE-100','Cap','Itraconazole B.P.','100 mg','10x1x10','Blister','1,600.00','360');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (68,'ITAZOLE-200','Cap','Itraconazole I.P.','200 mg','10x1x10','Blister','2,500.00','590');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (69,'ITAZOLE-T','Tab','Itraconazole B.P.','200 MG','10x10','Alu-Alu','3,000.00','690');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (70,'ITAZOLE-T','Tab','Terbinafine HCl','250 mg','10x10','Alu-Alu','3,000.00','690');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (71,'RD RED-XT Tab','Tab','Ferrous Ascorbate','100 mg','3 X 10','Alu-Alu','270','60');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (72,'RD RED-XT Tab','Tab','Folic Acid I.P.','1.5 Mg','3 X 10','Alu-Alu','270','60');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (73,'RD RED-XT Tab','Tab','Zinc SulphateI.P.','22.5 Mg','3 X 10','Alu-Alu','270','60');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (74,'ALBO','Tab','Albendazole I.P.','400 mg','1X5X5','Blister','450','75');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (75,'ALBO','Tab','Ivermectin I.P.','6 mg','1X5X5','Blister','450','75');
INSERT INTO products(id,Product,Type,Composition,Qty,Size,Packing,MRP,Net_Rate) VALUES (76,'ORNILEX-500','Tab','Ornidazole','500 mg','10 x 10','Blister','1,150.00','250');
